apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-demo
  namespace: pankaj
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: back-end
          image: CONTAINER_IMAGE  
          ports:
          - containerPort: 80
          - containerPort: 443
          livenessProbe:
            tcpSocket:
              port: 80
            initialDelaySeconds: 45
            failureThreshold: 1
            periodSeconds: 10
            timeoutSeconds: 10
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 4
            periodSeconds: 2
            failureThreshold: 3
          
